/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author diego
 */
public class PSorteio extends javax.swing.JPanel {
    private TPrincipal framePai = null;
    private Evento eventoSelecionado = null;
    private ArrayList<Aluno> arrayAlunosMatriculados = null;
    
    /**
     * Creates new form PSorteio
     */
    public PSorteio(TPrincipal framePai, Evento eventoSelecionado) {
        initComponents();
        this.framePai = framePai;
        this.eventoSelecionado = eventoSelecionado;
        
        arrayAlunosMatriculados = new ArrayList<>();        
                        
        String mensagem = "33;"+ eventoSelecionado.getCodEvento();
        try {
            framePai.getOut().writeUTF(mensagem);
            String resultServidor = null;
            resultServidor = framePai.getIn().readUTF();
            System.out.println(resultServidor);
            resultServidor.trim();
            String conteudo[] = resultServidor.split("\\|");

            //popula array
            System.out.println("Conteudo retorno 33" + conteudo[0]);
            System.out.println(Arrays.deepToString(conteudo));
            Aluno evt2;            
           
            for (int i = 1; i < conteudo.length; i++) {
                String descAluno[] = conteudo[i].split(";");
                evt2 = new Aluno();
                evt2.setCodAluno(descAluno[0]);
                evt2.setRa(descAluno[1]);
                evt2.setNome(descAluno[2]);
                evt2.setCurso(descAluno[3]);
                evt2.setPeriodo((descAluno[4]));
                evt2.setEmail(descAluno[5]);
                evt2.setTelefone(descAluno[6]);
                arrayAlunosMatriculados.add(evt2);
            }
        } catch(IOException ex){
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTNomeAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Sortear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeAlunoActionPerformed(evt);
            }
        });

        jLabel1.setText("Aluno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    
        
        int sizeArrayMatriculados = arrayAlunosMatriculados.size();
        if(sizeArrayMatriculados > 0){
            int valorSorteado = new Random().nextInt(sizeArrayMatriculados);
            jTNomeAluno.setText(arrayAlunosMatriculados.get(valorSorteado).getNome());        
        } else {
             JOptionPane.showMessageDialog(null, "Nenhum Aluno Presente!", "Erro", ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTNomeAluno;
    // End of variables declaration//GEN-END:variables
}
